[package]
name = "include-lua-macro"
version = "0.1.0"
repository = "https://github.com/AlphaModder/include-lua"
license = "MIT"
authors = ["AlphaModder"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
walkdir = "2.2"
proc-macro-hack = "0.5.4"
